[global]
line_length = 0
force_exclude = true

exclude = [
    ".git",
    "dist",
    "build",
    "CHANGELOG.md",
]

respect_gitignore = true

[MD013]
reflow = true
reflow_mode = "sentence_per_line"
