[workspace]
resolver = "3"
members = ["."]

[workspace.package]
edition = "2024"

[workspace.dependencies]
pyo3 = "0.27.0"

[package]
name = "twirl"
version = "0.0.2"
edition = "2024"
license = "GPL-2.0-only"

[lib]
name = "twirl"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
