[package]
name = "pearl"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pearl"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
once_cell = "1.21.3"
pyo3 = "0.25.0"
tree-sitter = "0.25.8"
tree-sitter-c = "0.24.1"
tree-sitter-cpp = "0.23.4"
tree-sitter-java = "0.23.5"
tree-sitter-javascript = "0.23.1"
tree-sitter-julia = "0.23.1"
tree-sitter-python = "0.23.6"
tree-sitter-rust = "0.24.0"
tree-sitter-typescript = "0.23.2"

[build-dependencies]
cc = "1.2.34"
