[package]
name = "loom"
version = "0.0.1"
edition = "2021"

[lib]
name = "loom"
crate-type = ["cdylib", "rlib"]

[dependencies]
arborium = "2.4.7"
git2 = "0.20.3"
pyo3 = "0.25.0"

[build-dependencies]
cc = "1.2.34"
